name: "Release AUR package"

on:
  push:
     tags:
       - '*'


jobs:
  build:
    name: "Release AUR package"
    runs-on: 'ubuntu-16.04'
    
    steps:
    - uses: actions/checkout@v2

    - name: Check beta
      id: check_beta
      run: |
        VERSION = ${GITHUB_REF/refs\/tags\//}
        read STABLE_VERSION < .ci/STABLE_VERSION
        if [ "${VERSION:0:${#STABLE_VERSION}}" == "$STABLE_VERSION" ]; then
          echo ::set-output name=ISBETA::false
        else
          echo ::set-output name=ISBETA::true
        fi

    - name: Install SSH key
      if: ! steps.check_beta.outputs.ISBETA
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa 
        known_hosts: ${{ secrets.KNOWN_HOST }}

    - name: Install Qt
      if: ! steps.check_beta.outputs.ISBETA
      run: |
        sudo add-apt-repository ppa:beineri/opt-qt-5.12.7-xenial -y
        sudo apt-get update -qq
        sudo apt-get -y install qt512base libgl1-mesa-dev qt512svg qt512imageformats
        bash /opt/qt*/bin/qt*-env.sh

    - name: Generate AUR files
      if: ! steps.check_beta.outputs.ISBETA
      run: |
        mkdir build
        git submodule update --init
        cd build
        cmake ..

    - name: Fetch AUR Remote
      if: ! steps.check_beta.outputs.ISBETA
      run: |
        git clone ssh://aur@aur.archlinux.org/cpeditor.git
        cd cpeditor
        rm PKGBUILD .SRCINFO
        mv ../build/aur/PKGBUILD .
        mv ../build/aur/.SRCINFO .

    - name: Publish to AUR
      if: ! steps.check_beta.outputs.ISBETA
      run: |
        cd cpeditor
        git config --global user.email "ashar786khan@gmail.com"
        git config --global user.name "coder3101"
        git add .
        git commit -m "New update from CI"
        git push -u origin master
