name: "CI: Build Test"

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        qt_version: [5.12.7, 5.14.1]
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ${RUNNER_WORKSPACE}/Qt
        key: ${{ matrix.platform }}-${{ matrix.qt_version }}-Qt

    - name: Install Qt
      uses: ouuan/install-qt-action@v2.4.0
      with:
        variableonly: steps.cache-qt.outputs.cache-hit
        version: ${{ matrix.qt_version }}
    
    - name: get submodules
      run: git submodule update --init --recursive

    - name: Cache build directory
      uses: actions/cache@v1
      with:
        path: ./build
        key: ${{ matrix.platform }}-${{ matrix.qt_version }}-build

    - name: make
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .
